repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        types_or: [ python, pyi ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        args: [--config-file, ./pyproject.toml]
        exclude: "tests.*"